# SentinelGate Yocto layer configuration
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sentinelgate"
BBFILE_PATTERN_sentinelgate = "^${LAYERDIR}/"
BBFILE_PRIORITY_sentinelgate = "6"

# Tested metadata targets. Adjust if using a newer Yocto release.
LAYERSERIES_COMPAT_sentinelgate = "scarthgap styhead walnascar"
